first homework
matveeva-s/2018-FS-11-Frontend-Matveeva pull request #12
Opened 2019-03-18 14:54 UTC by matveeva-s

Привет. Сделала первое дз, добавила 6 смайлов.

2019-03-19 20:26 UTC, chexex reviewed
Сразу скажу, что я вижу здесь достаточные знания и технику для решений задач в веб разработке. 
Между тем, обращу внимание на необходимость дотянуть уровень по реакту (jsx, состояния, взаимодействие между компонентами).
Спасибо за работу :)

2019-03-19 20:26 UTC, chexex commented on src/components/App.css
> +}
Предлагаю рассмотреть возможность использовать одну картинку, вместо 6 разных (оптимизация для http1.1, sprite)

2019-03-19 20:26 UTC, chexex commented on src/components/App.css
>  }
У трех элементов выше определена абсолютная позиция. В случае, когда мы самостоятельно заполняем файл со стилями, предложу рассмотреть вариант с элементом-контейнером, в котором можно записать дочерние элементы (кнопки), не используя абсолютных позиций, либо не используя крупных значений при задании положения элемента. 
1. Рекомендую использовать экосистему реакта для работы со стилями (styled css, module css) 
2. Рекомендую избегать абсолютных позиций относительно крупных блоков (адаптивность)

2019-03-19 20:26 UTC, chexex commented on src/components/Chat.js
> +        document.getElementById("hidden").value = document.getElementById("form-input").innerHTML;
Так делать можно (можно делать что угодно, лишь бы в итоге работало приложение), но правильнее использовать встроенные возможности реакта :) 
https://stackoverflow.com/a/36683831 (второй вариант: React 16 (and 15.5 transitional) and 'modern' JS)

2019-03-19 20:26 UTC, chexex commented on src/components/Chat.js
> +        });
Предлагаю посмотреть в сторону jsx :)

2019-03-19 20:26 UTC, chexex commented on src/components/Chat.js
> +        if (document.getElementById('form-input').innerHTML === '') {
Перевести работу с инпутом на реакт

2019-03-19 20:26 UTC, chexex commented on src/components/Chat.js
> +             return false;
Можно опустить `false`

2019-03-19 20:26 UTC, chexex commented on src/components/Chat.js
> +        document.getElementById('result').appendChild(message);
Перейти на jsx :) 

```js
const Result = ({msg}) => (
  <div>
    <p>{msg}</p>
  </div>
)

... 

<Result msg={this.state.inputValue} />
```

2019-03-19 20:26 UTC, chexex commented on src/components/Chat.js
> +        em6.addEventListener("click", this.handleClickEmoticon);
Относительно 6 строк выше:
Если допустить обсуждение этих строк вне какого-либо контекста, то рекомендую обратить внимание на тему погружения и всплытия события. 
В данном случае, можно было бы добавить обработчик событий только на `emoticonsDiv` и проверять, является ли `event.currentTarget` нужным элементом :)

2019-03-20 05:55 UTC, martinkomitsky commented on src/components/App.css
> +}
Имеется ввиду, что это условие самого ДЗ - сделать спрайты)

2019-03-20 05:58 UTC, martinkomitsky commented on src/components/Chat.js
> +        em6.addEventListener("click", this.handleClickEmoticon);
Но если смотреть в сторону ДЗ и курса в целом, то надо использовать встроенные возможности React

2019-03-20 05:59 UTC, martinkomitsky requested changes
Исправить замечания. Выполнить условия из ДЗ

2019-03-25 22:08 UTC, matveeva-s commented on src/components/App.css
> +}
Объединила смайлики в спрайт (класс emoticon, в котором на фоне картинка со спрайтом) и сделала для каждого отдельный класс (bg1, ... , bg6) - с положением нужного смайлика на спрайте. Самому объекту-смайлику присваивается двойной класс "emoticon bgN" (из одного берется сам фон-спрайт, из другого - положение на этом фоне) - насколько я поняла это как-то так должно работать.

2019-03-25 22:15 UTC, matveeva-s commented on src/components/App.css
>  }
Переделала всю форму отправки сообщения - теперь у формы два дочерних элемента: блок contentEditable для написания сообщения и блок со всеми кнопками.
В блоке с кнопками работает flex - он сам выравнивает дочерние элементы-кнопки в колонку, поэтому явно задавать позицию каждой кнопки больше не нужно.

2019-03-25 22:16 UTC, matveeva-s commented on src/components/Chat.js
> +        document.getElementById("hidden").value = document.getElementById("form-input").innerHTML;
Этот обработчик более не используется.

2019-03-25 22:22 UTC, matveeva-s commented on src/components/Chat.js
> +        });
Оставила тут все как есть, увы пока не шарю нормально за react и jsx. Надеюсь можно будет параллельно с дз изучать и переписывать все на реакт :)

2019-03-25 22:25 UTC, matveeva-s commented on src/components/Chat.js
> +             return false;
Сделала уже после того как закоммитила (поверьте на слово).

2019-03-25 22:26 UTC, matveeva-s commented on src/components/Chat.js
> +        if (document.getElementById('form-input').innerHTML === '') {
Как только заботаю нормально реакт :(

2019-03-25 22:27 UTC, matveeva-s commented on src/components/Chat.js
> +        em6.addEventListener("click", this.handleClickEmoticon);
Во избежание копипаста этих 6 строк завела массив со смайликами и единым обработчиком.

2019-03-25 22:30 UTC, matveeva-s commented on src/components/Chat.js
> +        document.getElementById('result').appendChild(message);
Как только заботаю нормально реакт :(

2019-06-04 15:56 UTC, closed without merging