Second hw
matveeva-s/2018-FS-11-Frontend-Matveeva pull request #2
Opened 2018-10-17 21:06 UTC by matveeva-s

Not done, but I'm in process.

2018-10-18 14:56 UTC, martinkomitsky requested changes
ДЗ не сделано.
В следующий раз накажу, а сейчас - срочно доделывай.

2018-11-03 15:44 UTC, matveeva-s commented
Привет, я тут пнула себя и доделала кажется второе дз.
Не совсем понятно, до какой степени надо стилизовать форму. Я сделала блок для того, чтобы сообщения выводились, шапку с именем и статусом(онлайн/не онлайн) собеседника, и аватаркой. 
Но аватарка лежит в dist, который в gitignore, т.е. она отображаться не будет.
И я ничего не исправляла eslint-ом, потому что там большинство кода Бориса, если надо - сделаю. 
В основной директории в файле utils.js лежит функция getReadableSize().

2018-11-04 07:37 UTC, martinkomitsky approved these changes

2018-11-04 07:40 UTC, martinkomitsky commented
Мы настраивали с тобой линтер для того, чтобы им пользоваться. Привыкай, что когда ты пишешь код, он должен быть в одном стиле и чист для визуальных проверок (мной, или твоими будущими коллегами).

Так что, даже если чей-то чужой код попал в коммит, то ты теперь автор, и вопросы потом будут к тебе, поэтому надо следить за кодом)

Давай ускоряться, тут максимум поставлю, а исправишь в след дз.

2018-11-04 07:40 UTC, merged