thirdHW
matveeva-s/2018-FS-11-Frontend-Matveeva pull request #3
Opened 2018-11-14 08:56 UTC by matveeva-s

2018-11-14 09:02 UTC, matveeva-s commented
Привет :)
1) Если что я не делала бонусное задание, но если надо сделаю.
2) Пофиксила табы на двойные пробелы где смогла, как просил линтер.
3) Есть проблема с тем, что я не знаю как стирать старые элементы из формы (забыла вчера спросить), поэтому приходится ручками проверять, не совпадает ли сообщение/файл/картинка с тем, что мы уже отправили раньше. Но думаю там стоит понять как чистить this._elements.form.elements, чтобы не костылить :(

2018-11-18 08:42 UTC, martinkomitsky requested changes
так тебе же без разницы, есть там что-то или нет
просто каждый раз при отправке делаешь очистку value инпута.

Еще надо исправить ошибки в консоли:
![image](https://user-images.githubusercontent.com/14847018/48670330-0d0ce180-eb27-11e8-94eb-8169f3a4f97d.png)

2018-11-20 18:59 UTC, martinkomitsky approved these changes

2018-11-20 18:59 UTC, martinkomitsky commented on npm-debug.log
> +0 info it worked if it ends with ok
Этот файл не нужен))

2018-11-20 18:59 UTC, merged

2018-11-20 18:59 UTC, martinkomitsky commented
5